/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form;

import java.util.logging.Level;
import java.util.logging.Logger;
import ui.form.gost.GostForma;
import ui.form.gost.PretragaGostaForma;
import ui.form.narudzbina.NarudzbinaForma;
import ui.form.narudzbina.PretragaNarudzbineForma;
import ui.form.terminDezurstva.TerminDezurstvaForma;

/**
 *
 * @author Sreja
 */
public class GlavnaForma extends javax.swing.JFrame {

    /**
     * Creates new form GlavnaForma
     */
    public GlavnaForma() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuGost = new javax.swing.JMenu();
        jMenuItemKreirajGosta = new javax.swing.JMenuItem();
        jMenuItemPretraziGoste = new javax.swing.JMenuItem();
        jMenuNarudzbina = new javax.swing.JMenu();
        jMenuItemKreirajNarudzbinu = new javax.swing.JMenuItem();
        jMenuItemPretraziNarudzbine = new javax.swing.JMenuItem();
        jMenuTerminDezurstva = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu8.setText("File");
        jMenuBar3.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar3.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nikola\\Desktop\\Restoran.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 280));

        jMenuGost.setText("Gost");

        jMenuItemKreirajGosta.setText("Kreiraj gosta");
        jMenuItemKreirajGosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajGostaActionPerformed(evt);
            }
        });
        jMenuGost.add(jMenuItemKreirajGosta);

        jMenuItemPretraziGoste.setText("Pretrazi goste");
        jMenuItemPretraziGoste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziGosteActionPerformed(evt);
            }
        });
        jMenuGost.add(jMenuItemPretraziGoste);

        jMenuBar2.add(jMenuGost);

        jMenuNarudzbina.setText("Narudzbina");

        jMenuItemKreirajNarudzbinu.setText("Kreiraj narudzbinu");
        jMenuItemKreirajNarudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemKreirajNarudzbinuActionPerformed(evt);
            }
        });
        jMenuNarudzbina.add(jMenuItemKreirajNarudzbinu);

        jMenuItemPretraziNarudzbine.setText("Pretrazi narudzbine");
        jMenuItemPretraziNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPretraziNarudzbineActionPerformed(evt);
            }
        });
        jMenuNarudzbina.add(jMenuItemPretraziNarudzbine);

        jMenuBar2.add(jMenuNarudzbina);

        jMenuTerminDezurstva.setText("Termin dezurstva");

        jMenuItem5.setText("Ubaci termin dezurstva");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenuTerminDezurstva.add(jMenuItem5);

        jMenuBar2.add(jMenuTerminDezurstva);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemPretraziGosteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziGosteActionPerformed
        try {
            PretragaGostaForma pgf = new PretragaGostaForma();
            pgf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretraziGosteActionPerformed

    private void jMenuItemKreirajGostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajGostaActionPerformed
        try {
            GostForma gf = new GostForma();
            gf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemKreirajGostaActionPerformed

    private void jMenuItemKreirajNarudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemKreirajNarudzbinuActionPerformed
        try {
            NarudzbinaForma nf = new NarudzbinaForma();
            nf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemKreirajNarudzbinuActionPerformed

    private void jMenuItemPretraziNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPretraziNarudzbineActionPerformed
        try {
            PretragaNarudzbineForma pnf = new PretragaNarudzbineForma();
            pnf.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GlavnaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItemPretraziNarudzbineActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        TerminDezurstvaForma tdf = new TerminDezurstvaForma();
        tdf.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlavnaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlavnaForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuGost;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemKreirajGosta;
    private javax.swing.JMenuItem jMenuItemKreirajNarudzbinu;
    private javax.swing.JMenuItem jMenuItemPretraziGoste;
    private javax.swing.JMenuItem jMenuItemPretraziNarudzbine;
    private javax.swing.JMenu jMenuNarudzbina;
    private javax.swing.JMenu jMenuTerminDezurstva;
    // End of variables declaration//GEN-END:variables
}
