/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.narudzbina;

import domain.Gost;
import domain.Jelo;
import domain.Narudzbina;
import domain.StavkaNarudzbine;
import domain.Zaposleni;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import table.models.ModelTabeleStavkeNarudzbine;
import ui.controller.ClientController;

/**
 *
 * @author Sreja
 */
public class NarudzbinaForma extends javax.swing.JFrame {

    private Narudzbina narudzbina;
    private List<Zaposleni> listaZaposlenih;
    private List<Gost> gosti;
    private List<Jelo> jela;
    private List<StavkaNarudzbine> stavkeNarudzbine;
    private JComboBox<Jelo> jComboBoxJela;
    private ModelTabeleStavkeNarudzbine mtsn;
    private PretragaNarudzbineForma pnf;

    /**
     * Creates new form NarudzbinaForma
     */
    public NarudzbinaForma() throws Exception {
        initComponents();
        popuniComboBoxZaposlenima();
        popuniComboBoxGostima();
        popuniComboBoxJelima();
        stavkeNarudzbine = new ArrayList<>();
        postaviModelTabeleStavkeNarudzbine();
        jButtonZapamti.setEnabled(false);
        setLocationRelativeTo(null);
        postaviDanasnjiDatum();
    }

    public Narudzbina getNarudzbina() {
        return narudzbina;
    }

    public void setNarudzbina(Narudzbina narudzbina) {
        this.narudzbina = narudzbina;
    }

    public PretragaNarudzbineForma getPnf() {
        return pnf;
    }

    public void setPnf(PretragaNarudzbineForma pnf) {
        this.pnf = pnf;
    }

    public JButton getjButtonKreiraj() {
        return jButtonKreiraj;
    }

    public void setjButtonKreiraj(JButton jButtonKreiraj) {
        this.jButtonKreiraj = jButtonKreiraj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavkeNarudzbine = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDatumVreme = new javax.swing.JTextField();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxGosti = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelDatum = new javax.swing.JLabel();
        jButtonKreiraj = new javax.swing.JButton();
        jButtonZapamti = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jButtonDodajStavku = new javax.swing.JButton();
        jButtonObrisiStavku = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableStavkeNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableStavkeNarudzbine);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Vreme:");

        jLabel2.setText("Status:");

        jLabel5.setText("Zaposleni:");

        jLabel7.setText("Gost:");

        jLabel8.setText("Format: HH:mm");

        jLabel3.setText("Datum:");

        jLabelDatum.setText("jLabel4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDatumVreme, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(jTextFieldStatus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBoxGosti, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxGosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldDatumVreme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelDatum))
                        .addGap(17, 17, 17))))
        );

        jButtonKreiraj.setText("Kreiraj");
        jButtonKreiraj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKreirajActionPerformed(evt);
            }
        });

        jButtonZapamti.setText("Zapamti");
        jButtonZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZapamtiActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jButtonDodajStavku.setText("Dodaj stavku");
        jButtonDodajStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajStavkuActionPerformed(evt);
            }
        });

        jButtonObrisiStavku.setText("Obrisi stavku");
        jButtonObrisiStavku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiStavkuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDodajStavku)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButtonOtkazi)
                        .addComponent(jButtonObrisiStavku)))
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButtonKreiraj)
                        .addGap(76, 76, 76)
                        .addComponent(jButtonZapamti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDodajStavku)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonObrisiStavku)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKreiraj)
                    .addComponent(jButtonZapamti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOtkazi)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKreirajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKreirajActionPerformed
        try {
            narudzbina = ClientController.getInstance().kreirajNarudzbina(new Narudzbina());
            JOptionPane.showMessageDialog(this, "Sistem je kreirao narudzbinu!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            jButtonKreiraj.setEnabled(false);
            jButtonZapamti.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da kreira narudzbinu!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKreirajActionPerformed

    private void jButtonZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZapamtiActionPerformed
        try {
            if (jComboBoxZaposleni.getSelectedItem() == null || jComboBoxGosti.getSelectedItem() == null || jTextFieldDatumVreme.getText().equals("")
                    || jTextFieldStatus.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Sva polja moraju biti popunjena!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            Zaposleni zaposleni = (Zaposleni) jComboBoxZaposleni.getSelectedItem();
            Gost gost = (Gost) jComboBoxGosti.getSelectedItem();
            Date danasnjiDatum = new Date();
            SimpleDateFormat datumFormat = new SimpleDateFormat("dd.MM.yyyy");
            String danasnjiDatumString = datumFormat.format(danasnjiDatum);
            Date datumIVreme = null;
            SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy HH:mm");
            try {
                datumIVreme = format.parse(danasnjiDatumString + " " + jTextFieldDatumVreme.getText());
                System.out.println(datumIVreme);
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(this, "Datum i vreme nisu u dobrom formatu!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            String status = jTextFieldStatus.getText();
            stavkeNarudzbine = mtsn.getStavkePlana();
            if (stavkeNarudzbine.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Narudzbina mora imati barem jednu stavku narudzbine!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            for (StavkaNarudzbine stavkaNarudzbine : stavkeNarudzbine) {
                if (stavkaNarudzbine.getJelo() == null || stavkaNarudzbine.getKolicina() == 0 || stavkaNarudzbine.getNapomena() == null) {
                    JOptionPane.showMessageDialog(this, "Sva polja u tabeli moraju biti popunjena!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            Narudzbina novaNarudzbina = new Narudzbina(datumIVreme, status, zaposleni, gost, stavkeNarudzbine);
            novaNarudzbina.setIdNarudzbina(narudzbina.getIdNarudzbina());
            ClientController.getInstance().promeniNarudzbina(novaNarudzbina);
            if (jButtonKreiraj.isVisible()) {
                isprazniPolja();
                jButtonKreiraj.setEnabled(true);
                jButtonZapamti.setEnabled(false);
            } else {
                pnf.popuniTabeluNarudzbine();
            }
            JOptionPane.showMessageDialog(this, "Sistem je zapamtio narudzbinu!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da zapamti narudzbinu!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonZapamtiActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    private void jButtonDodajStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajStavkuActionPerformed
        StavkaNarudzbine stavkaNarudzbine = new StavkaNarudzbine();
        mtsn.dodajStavku(stavkaNarudzbine);
    }//GEN-LAST:event_jButtonDodajStavkuActionPerformed

    private void jButtonObrisiStavkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiStavkuActionPerformed
        int selektovaniRed = jTableStavkeNarudzbine.getSelectedRow();
        if (selektovaniRed == -1) {
            JOptionPane.showMessageDialog(this, "Niste izabrali stavku narudzbine!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
            return;
        }
        mtsn.obrisiStavku(selektovaniRed);
    }//GEN-LAST:event_jButtonObrisiStavkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NarudzbinaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NarudzbinaForma().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(NarudzbinaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajStavku;
    private javax.swing.JButton jButtonKreiraj;
    private javax.swing.JButton jButtonObrisiStavku;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonZapamti;
    private javax.swing.JComboBox<Object> jComboBoxGosti;
    private javax.swing.JComboBox<Object> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDatum;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStavkeNarudzbine;
    private javax.swing.JTextField jTextFieldDatumVreme;
    private javax.swing.JTextField jTextFieldStatus;
    // End of variables declaration//GEN-END:variables

    private void popuniComboBoxZaposlenima() throws Exception {
        listaZaposlenih = ClientController.getInstance().vratiListuSviZaposleni();
        jComboBoxZaposleni.setModel(new DefaultComboBoxModel<>(listaZaposlenih.toArray()));
        jComboBoxZaposleni.setSelectedItem(null);
    }

    private void popuniComboBoxGostima() throws Exception {
        gosti = ClientController.getInstance().vratiListuSviGost();
        jComboBoxGosti.setModel(new DefaultComboBoxModel<>(gosti.toArray()));
        jComboBoxGosti.setSelectedItem(null);
    }

    private void postaviModelTabeleStavkeNarudzbine() {
        mtsn = new ModelTabeleStavkeNarudzbine(stavkeNarudzbine);
        jTableStavkeNarudzbine.setModel(mtsn);
        mtsn.setNf(this);
        jTableStavkeNarudzbine.getColumnModel().getColumn(0).setPreferredWidth(5);
        jTableStavkeNarudzbine.getColumnModel().getColumn(1).setPreferredWidth(100);
        jTableStavkeNarudzbine.getColumnModel().getColumn(1).setCellEditor(new DefaultCellEditor(jComboBoxJela));
        jTableStavkeNarudzbine.getColumnModel().getColumn(2).setPreferredWidth(10);
        jTableStavkeNarudzbine.getColumnModel().getColumn(3).setPreferredWidth(10);
        jTableStavkeNarudzbine.getColumnModel().getColumn(4).setPreferredWidth(10);
        jTableStavkeNarudzbine.getColumnModel().getColumn(5).setPreferredWidth(50);
    }

    private void popuniComboBoxJelima() throws Exception {
        jComboBoxJela = new JComboBox<>();
        jela = ClientController.getInstance().vratiListuSviJelo();
        DefaultComboBoxModel<Jelo> jeloModel = new DefaultComboBoxModel<>(jela.toArray(new Jelo[0]));
        jComboBoxJela.setModel(jeloModel);
    }

    void popuniPolja() {
        jComboBoxZaposleni.setSelectedItem(narudzbina.getZaposleni());
        jComboBoxGosti.setSelectedItem(narudzbina.getGost());
        SimpleDateFormat format = new SimpleDateFormat("HH:mm");
        jTextFieldDatumVreme.setText(format.format(narudzbina.getDatumIVreme()));
        jTextFieldStatus.setText(narudzbina.getStatus());
        stavkeNarudzbine = narudzbina.getStavkeNarudzine();
        postaviModelTabeleStavkeNarudzbine();
        jButtonZapamti.setEnabled(true);
        format = new SimpleDateFormat("dd.MM.yyyy");
        jLabelDatum.setText(format.format(narudzbina.getDatumIVreme()));
    }

    void onemoguciPolja() {
        jTextFieldDatumVreme.setEditable(false);
        jTextFieldStatus.setEditable(false);
        jComboBoxZaposleni.setEnabled(false);
        jComboBoxGosti.setEnabled(false);
        jTableStavkeNarudzbine.setEnabled(false);
        jButtonDodajStavku.setEnabled(false);
        jButtonObrisiStavku.setEnabled(false);
        jButtonKreiraj.setVisible(false);
        jButtonZapamti.setVisible(false);
    }

    private void isprazniPolja() {
        jComboBoxZaposleni.setSelectedItem(null);
        jComboBoxGosti.setSelectedItem(null);
        jTextFieldDatumVreme.setText("");
        jTextFieldStatus.setText("");
        stavkeNarudzbine = new ArrayList<>();
        postaviModelTabeleStavkeNarudzbine();
        jButtonKreiraj.setEnabled(true);
        jButtonZapamti.setEnabled(false);
    }

    private void postaviDanasnjiDatum() {
        SimpleDateFormat format = new SimpleDateFormat("dd.MM.yyyy");
        jLabelDatum.setText(format.format(new Date()));
    }
}
