/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.narudzbina;

import domain.Gost;
import domain.Narudzbina;
import domain.Zaposleni;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import table.models.ModelTabeleNarudzbine;
import ui.controller.ClientController;

/**
 *
 * @author Sreja
 */
public class PretragaNarudzbineForma extends javax.swing.JFrame {

    private Narudzbina narudzbina;
    private List<Narudzbina> narudzbine;
    private List<Zaposleni> listaZaposlenih;
    private List<Gost> gosti;

    /**
     * Creates new form PretragaNarudzbineForma
     */
    public PretragaNarudzbineForma() throws Exception {
        initComponents();
        popuniComboBoxZaposlenima();
        popuniComboBoxGostima();
        popuniTabeluNarudzbine();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxZaposleni = new javax.swing.JComboBox<>();
        jComboBoxGosti = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNarudzbine = new javax.swing.JTable();
        jButtonDetaljiNarudzbine = new javax.swing.JButton();
        jButtonIzmeniNarudzbinu = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();
        jButtonOsvezi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Odaberite zaposlenog:");

        jLabel2.setText("Odaberite gosta:");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jTableNarudzbine.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableNarudzbine);

        jButtonDetaljiNarudzbine.setText("Detalji narudzbine");
        jButtonDetaljiNarudzbine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDetaljiNarudzbineActionPerformed(evt);
            }
        });

        jButtonIzmeniNarudzbinu.setText("Izmeni narudzbinu");
        jButtonIzmeniNarudzbinu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIzmeniNarudzbinuActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        jButtonOsvezi.setText("Osvezi");
        jButtonOsvezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsveziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxGosti, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(jButtonDetaljiNarudzbine))
                        .addComponent(jButtonOsvezi, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButtonOtkazi))
                    .addComponent(jButtonIzmeniNarudzbinu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxGosti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPretrazi)
                            .addComponent(jButtonOsvezi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDetaljiNarudzbine)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonIzmeniNarudzbinu))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            if (jComboBoxZaposleni.getSelectedItem() == null && jComboBoxGosti.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Morate odabrati zaposlenog ili gosta!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            narudzbina = new Narudzbina();
            narudzbina.setZaposleni((Zaposleni) jComboBoxZaposleni.getSelectedItem());
            narudzbina.setGost((Gost) jComboBoxGosti.getSelectedItem());
            narudzbine = ClientController.getInstance().vratiListuNarudzbina(narudzbina);
            postaviModelTabeleNarudzbine();
            if (narudzbine.isEmpty()) {
                throw new Exception();
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao narudzbine po zadatim kriterijumima!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje narudzbine po zadatim kriterijumima!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonDetaljiNarudzbineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDetaljiNarudzbineActionPerformed
        try {
            int selektovaniRed = jTableNarudzbine.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali narudzbinu!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            narudzbina = narudzbine.get(selektovaniRed);
            narudzbina = ClientController.getInstance().pretraziNarudzbina(narudzbina);
            JOptionPane.showMessageDialog(this, "Sistem je nasao narudzbinu!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            NarudzbinaForma nf = new NarudzbinaForma();
            nf.setNarudzbina(narudzbina);
            nf.popuniPolja();
            nf.onemoguciPolja();
            nf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje narudzbinu!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDetaljiNarudzbineActionPerformed

    private void jButtonIzmeniNarudzbinuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIzmeniNarudzbinuActionPerformed
        try {
            int selektovaniRed = jTableNarudzbine.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali narudzbinu!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            narudzbina = narudzbine.get(selektovaniRed);
            narudzbina = ClientController.getInstance().pretraziNarudzbina(narudzbina);
            JOptionPane.showMessageDialog(this, "Sistem je nasao narudzbinu!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            NarudzbinaForma nf = new NarudzbinaForma();
            nf.setPnf(this);
            nf.setNarudzbina(narudzbina);
            nf.popuniPolja();
            nf.getjButtonKreiraj().setVisible(false);
            nf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje narudzbinu!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonIzmeniNarudzbinuActionPerformed

    private void jButtonOsveziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsveziActionPerformed
        try {
            popuniTabeluNarudzbine();
            jComboBoxGosti.setSelectedItem(null);
            jComboBoxZaposleni.setSelectedItem(null);
        } catch (Exception ex) {
            Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOsveziActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PretragaNarudzbineForma().setVisible(true);
                } catch (Exception ex) {
                    java.util.logging.Logger.getLogger(PretragaNarudzbineForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDetaljiNarudzbine;
    private javax.swing.JButton jButtonIzmeniNarudzbinu;
    private javax.swing.JButton jButtonOsvezi;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JComboBox<Object> jComboBoxGosti;
    private javax.swing.JComboBox<Object> jComboBoxZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNarudzbine;
    // End of variables declaration//GEN-END:variables

    private void postaviModelTabeleNarudzbine() {
        ModelTabeleNarudzbine mtn = new ModelTabeleNarudzbine(narudzbine);
        jTableNarudzbine.setModel(mtn);
        jTableNarudzbine.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTableNarudzbine.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTableNarudzbine.getColumnModel().getColumn(2).setPreferredWidth(60);
    }

    private void popuniComboBoxZaposlenima() throws Exception {
        listaZaposlenih = ClientController.getInstance().vratiListuSviZaposleni();
        jComboBoxZaposleni.setModel(new DefaultComboBoxModel<>(listaZaposlenih.toArray()));
        jComboBoxZaposleni.setSelectedItem(null);
    }

    private void popuniComboBoxGostima() throws Exception {
        gosti = ClientController.getInstance().vratiListuSviGost();
        jComboBoxGosti.setModel(new DefaultComboBoxModel<>(gosti.toArray()));
        jComboBoxGosti.setSelectedItem(null);
    }

    public void popuniTabeluNarudzbine() throws Exception {
        narudzbine = ClientController.getInstance().vratiListuSviNarudzbina();
        postaviModelTabeleNarudzbine();
    }
}
