/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.form.gost;

import domain.Gost;
import domain.Grad;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import table.models.ModelTabeleGosti;
import ui.controller.ClientController;

/**
 *
 * @author Sreja
 */
public class PretragaGostaForma extends javax.swing.JFrame {

    private Gost gost;
    private List<Grad> gradovi;
    private List<Gost> gosti;

    /**
     * Creates new form PretragaGostaForma
     */
    public PretragaGostaForma() throws Exception {
        initComponents();
        popuniComboBoxGradovima();
        popuniTabeluGostima();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBoxGradovi = new javax.swing.JComboBox<>();
        jButtonPretrazi = new javax.swing.JButton();
        jButtonOsvezi = new javax.swing.JButton();
        jButtonPromeniSportistu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGosti = new javax.swing.JTable();
        jButtonObrisiSportistu = new javax.swing.JButton();
        jButtonOtkazi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Izaberite grad:");

        jButtonPretrazi.setText("Pretrazi");
        jButtonPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPretraziActionPerformed(evt);
            }
        });

        jButtonOsvezi.setText("Osvezi");
        jButtonOsvezi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOsveziActionPerformed(evt);
            }
        });

        jButtonPromeniSportistu.setText("Promeni gosta");
        jButtonPromeniSportistu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromeniSportistuActionPerformed(evt);
            }
        });

        jTableGosti.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableGosti);

        jButtonObrisiSportistu.setText("Obrisi gosta");
        jButtonObrisiSportistu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrisiSportistuActionPerformed(evt);
            }
        });

        jButtonOtkazi.setText("Otkazi");
        jButtonOtkazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOtkaziActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jButtonOtkazi)
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButtonPretrazi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOsvezi)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPromeniSportistu)
                            .addComponent(jButtonObrisiSportistu, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxGradovi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPretrazi)
                    .addComponent(jButtonOsvezi))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonPromeniSportistu)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonObrisiSportistu)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOtkazi)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPretraziActionPerformed
        try {
            if (jComboBoxGradovi.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Morate odabrati grad!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            gost = new Gost();
            gost.setGrad((Grad) jComboBoxGradovi.getSelectedItem());
            gosti = ClientController.getInstance().vratiListuGost(gost);
            postaviModelTabeleGosti();
            if (gosti.isEmpty()) {
                throw new Exception();
            }
            JOptionPane.showMessageDialog(this, "Sistem je nasao goste po zadatim kriterijumima!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje goste po zadatim kriterijumima!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPretraziActionPerformed

    private void jButtonOsveziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOsveziActionPerformed
        try {
            popuniTabeluGostima();
            jComboBoxGradovi.setSelectedItem(null);
        } catch (Exception ex) {
            Logger.getLogger(PretragaGostaForma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonOsveziActionPerformed

    private void jButtonPromeniSportistuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromeniSportistuActionPerformed
        try {
            int selektovaniRed = jTableGosti.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali gosta!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            gost = gosti.get(selektovaniRed);
            gost = ClientController.getInstance().pretraziGost(gost);
            JOptionPane.showMessageDialog(this, "Sistem je nasao gosta!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            GostForma gf = new GostForma();
            gf.setPgf(this);
            gf.setGost(gost);
            gf.popuniPolja();
            gf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje gosta!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonPromeniSportistuActionPerformed

    private void jButtonObrisiSportistuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrisiSportistuActionPerformed
        try {
            int selektovaniRed = jTableGosti.getSelectedRow();
            if (selektovaniRed == -1) {
                JOptionPane.showMessageDialog(this, "Niste odabrali gosta!", "Upozorenje", JOptionPane.WARNING_MESSAGE);
                return;
            }
            gost = gosti.get(selektovaniRed);
            gost = ClientController.getInstance().pretraziGost(gost);
            JOptionPane.showMessageDialog(this, "Sistem je nasao gosta!", "Obavestenje!", JOptionPane.INFORMATION_MESSAGE);
            GostForma gf = new GostForma();
            gf.setPgf(this);
            gf.setGost(gost);
            gf.popuniPolja();
            gf.onemoguciPolja();
            gf.setVisible(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da nadje gosta!", "Greska!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonObrisiSportistuActionPerformed

    private void jButtonOtkaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOtkaziActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonOtkaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PretragaGostaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PretragaGostaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PretragaGostaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PretragaGostaForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PretragaGostaForma().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(PretragaGostaForma.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void popuniComboBoxGradovima() throws Exception {
        gradovi = ClientController.getInstance().vratiListuSviGrad();
        jComboBoxGradovi.setModel(new DefaultComboBoxModel<>(gradovi.toArray()));
        jComboBoxGradovi.setSelectedItem(null);
    }

    private void postaviModelTabeleGosti() {
        ModelTabeleGosti mtg = new ModelTabeleGosti(gosti);
        jTableGosti.setModel(mtg);
    }

    public void popuniTabeluGostima() throws Exception {
        gosti = ClientController.getInstance().vratiListuSviGost();
        postaviModelTabeleGosti();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonObrisiSportistu;
    private javax.swing.JButton jButtonOsvezi;
    private javax.swing.JButton jButtonOtkazi;
    private javax.swing.JButton jButtonPretrazi;
    private javax.swing.JButton jButtonPromeniSportistu;
    private javax.swing.JComboBox<Object> jComboBoxGradovi;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGosti;
    // End of variables declaration//GEN-END:variables
}
